export const dataArray = [
  {
    id: 1,
    title: "HTML",
    para: "The language for building web pages",
    btn1: "Learn HTML",
    btn1bg: "green",
    btn2: "Video Tutorial",
    btn2bg: "yellow",
    btn3: "HTML Reference",
    btn3bg: "lightblack",
    btn4: "Get Certified",
    btn4bg: "pink",
    bg: "lightgreen",
    content:
      " <!DOCTYPE html> \n <html> \n <head> \n <title> HTML TUTORIAL </title> \n </head> \n <body> \n <h1>This is a heading</h1>  \n   <p>This is a paragraph.</p> \n  </body> \n </html>",
    editorheading: "HTML Example : ",
  },
  {
    id: 2,
    title: "CSS",
    para: "The language for styling web pages",
    btn1: "Learn CSS",
    btn1bg: "green",
    btn2: "Video Tutorial",
    btn2bg: "white",
    btn3: "CSS Reference",
    btn3bg: "lightblack",
    btn4: "Get Certified",
    btn4bg: "pink",
    bg: "yellow",
    content:
      "body { \n background-color: lightblue;   \n }  \n  h1 {  \n  color: white;   text-align: center; \n } \n  p { \n font-family: verdana;  \n }\n",
    editorheading: "CSS Example : ",
  },
  {
    id: 3,
    title: "JavaScript",
    para: "The language for programming web pages",
    btn1: "Learn JavaScript",
    btn1bg: "green",
    btn2: "JavaScript Reference",
    btn2bg: "white",
    btn3: "Get Certified",
    btn3bg: "pink",
    bg: "lightblack",
    content:
      "<button onclick=myFunction()>Click Me! \n </button>\n\n  <script>\n function myFunction() { \n let x = \n document.getElementById(demo); \n x.style.fontSize = 25px; \n x.style.color = red; \n }\n </script>",
    editorheading: "JavaScript Example : ",
    textcolor: "blacktext",
  },
  {
    id: 4,
    title: "Python",
    para: "A Popular Programming Language",
    btn1: "Learn Python",
    btn1bg: "green",
    btn2: "Python Reference",
    btn2bg: "lightblack",
    btn3: "Get Certified",
    btn3bg: "pink",
    bg: "white",
    content: "if 5 > 2:  \n  print(Five is greater than two!)",
    editorheading: "Python Example : ",
  },
  {
    id: 5,
    title: "SQL",
    para: "A language for accessing databases",
    btn1: "Learn SQL",
    btn1bg: "green",
    btn2: "SQL Reference",
    btn2bg: "lightblack",
    btn3: "Get Certified",
    btn3bg: "pink",
    bg: "blue",
    content: "SELECT * FROM Customers \n WHERE Country='Mexico';",
    editorheading: "SQL Example : ",
  },
];
